version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.admin2=disabled
    ports:
      - 8080:8080